# Recurring activities
# Make the things that enrich you your hobby/passion/job
# ideas:
# balancing-ball; Sitting on a fitnessball behind desk at work (stimulating core)
# biking: We in the Netherlands bike a lot, which allows us to skip leg day
# moscow can be either: must, should, could or wont

portfolio_management:
  interval: weekly
  desc: Finances
  moscow: should
  energize: false # costs/burns mental energy
  flow: false # possible to get into flow state?
  maslow: safety
  goals:
  - finance
tidy:
  interval: daily
  energize: true # the result makes me feel good
  flow: false
  desc: digitally (e.g. notes) and physically (e.g. desk)
  moscow: should
  maslow: safety
  goals:
  - organized
prototype:
  interval: weekly
  moscow: should
  desc: Work out prototypes that could lead to a startup
  energize: true # hobby
  flow: true
  maslow: esteem
  goals:
  - prototype
plan:
  interval: daily
  moscow: must
  desc: on weekdays; plan day. In weekend; update long-term planning
  energize: false # requires prefrontal cortex
  flow: false
  maslow: safety
  goals:
  - organized
shower:
  interval: daily
  moscow: must
  desc: wc, cold shower, shave, dental
  energize: true # feeling refreshed afterward
  flow: true
  maslow: physiological
news:
  interval: daily
  moscow: could
  desc: Daily news and hackernews
  energize: false
  flow: false
  maslow: belong
dress:
  interval: daily
  desc: Prepared the day before #After stretching, put cloths on, stretching is done in underwear
  moscow: must
  energize: false
  flow: false
  maslow: physiological
meditate:
  interval: daily
  desc: headspace
  moscow: should
  energize: true
  flow: true
  maslow: actualization
  goals:
  - rested
address_power:
  interval: daily
  desc: See benjamin franklin diary
  moscow: should
  energize: false
  flow: true
  maslow: actualization
  goals:
  - scriptures
guitar:
  interval: weekly
  desc: Just play
  moscow: could
  energize: true # enjoyable activity
  flow: true
  maslow: esteem
  goals:
  - songs
dental:
  interval: daily
  desc: Brushing earlier in the evening increases the likelihood of flossing and prevents late night snacks
  moscow: must
  energize: false
  flow: false
  maslow: physiological
dishwasher:
  interval: daily
  moscow: must
  energize: false
  flow: false
  maslow: physiological
  goals:
  - organized
food2fridge:
  interval: daily
  desc: from freezer to fridge
  moscow: should
  energize: false
  flow: false
  maslow: physiological
  goals:
  - organized
read:
  interval: daily
  desc: Book, no articles/screens
  moscow: should
  energize: true # dependant on the content
  flow: true
  maslow: actualization
  goals:
  - reader
audiobook:
  interval: daily
  desc: learn spanish during commute
  moscow: could
  energize: false # requires active listening
  flow: false
  maslow: actualization
day-review:
  interval: daily
  moscow: should
  desc: >
    What did I do good?
    Bad?
    Stuck in loops?
    What conversations do I need to have?
    What unmade decisions do I have?
    Helicopter overview
  energize: false
  flow: false
  maslow: esteem
message:
  interval: daily
  desc: >
    Work email
    Linkedin
    Private email
    Whatsapp
    Signal
    Telegram
    Fb
    Other apps.
  moscow: should
  energize: false
  flow: false
  maslow: belong
cook:
  interval: daily
  moscow: should
  energize: true
  flow: true
  desc: Food in slow cooker, quick wok or oven dish
  maslow: physiological
gratitude:
  interval: daily
  moscow: could
  energize: true
  flow: false
  maslow: belong
  goals:
  - focus
solarium:
  interval: daily
  energize: true
  flow: true
  moscow: could #during winter: wont
  desc: during the winter months
  maslow: physiological
bike:
  interval: weekly
  energize: true
  flow: depends
  desc: bike
  maslow: safety
lunch:
  interval: daily
  moscow: should
  energize: true
  flow: false
  desc: Walking and eating
  maslow: physiological
work:
  interval: daily
  moscow: must
  energize: false
  flow: depends
  maslow: safety
dinner:
  interval: daily
  moscow: should
  energize: true
  flow: true
  maslow: physiological
water:
  interval: daily
  moscow: must
  energize: true
  flow: false
  maslow: physiological
psychoanalysis:
  desc: self psychology
  moscow: should
  energize: false
  flow: true
  interval: weekly
  maslow: actualization
alarm:
  moscow: must
  desc: smartwatch, 3min later phone downstairs
  interval: daily
  energize: false
  flow: false
  maslow: physiological
wake_up:
  moscow: must
  desc: Actually wake up, drink water, urgent msgs, toilet
  interval: daily
  energize: false
  flow: false
  maslow: physiological
dream_diary:
  moscow: could
  desc: Part of lucid dreaming exercise
  interval: daily
  energize: true
  flow: true
  maslow: actualization
blog:
  moscow: could
  desc: Write, proof read or publish
  interval: daily
  energize: false
  flow: true
  maslow: esteem
photography:
  moscow: should
  desc: Practice with phone camera
  interval: daily
  energize: false
  flow: false
  maslow: belong


drive:
  moscow: must
  interval: weekly
  energize: false
  flow: true
  maslow: physiological
gasstation:
  moscow: must
  energize: true
  flow: false
  maslow: physiological


# Before Covid lockdown
museum:
  moscow: could
  desc: Visit museum
  energize: true
  flow: false
  interval: weekly
  maslow: belong
  goals:
  - museum
  - datenite
pack:
  interval: daily
  desc: bag and clothing
  moscow: should
  energize: false
  flow: false
  maslow: physiological
  goals:
  - organized
to_train:
  interval: daily
  energize: true
  flow: false
  desc: Bike/walk from/to train
  maslow: safety

# Student days
prepare-lecture:
  interval: weekly
  moscow: could
  energize: false
  flow: false
  desc: Prepare lecture
  maslow: esteem
lecture:
  interval: weekly
  moscow: should
  energize: false
  flow: false
  maslow: esteem
homework:
  interval: weekly
  moscow: must
  energize: false
  flow: depends
  maslow: esteem
ds:
  interval: weekly
  moscow: should
  energize: false
  flow: depends
  desc: Data Science
  maslow: esteem
band_rehearsal:
  interval: weekly
  energize: true
  flow: depends
  desc: Jamming
  moscow: must
  maslow: esteem

# Backup and restore every device once a month
# to make sure all data is properly backed up
backup:
  interval: weekly
  energize: false
  flow: false
  desc: >
    first sunday phone,
    second laptop,
    third server,
    fourth smart watch and ereader
    takeout.google.com
    Make sure google photos are converted to high quality, not original photos.google.com/quotamanagement
  moscow: should
  maslow: safety

update-resume:
  interval: monthly
  energize: false
  flow: false
  desc: Regurally update list of activities and tools used
  moscow: should
  maslow: safety

automation:
  interval: weekly
  energize: false
  flow: false
  moscow: should
  maslow: safety
  desc: |
    By first standardizing more parts of our life/work/business
    we enable as a second step to outsource or automate these parts.
    Using standardized tooling/processes enables outsourcing.



# fitness
## Endurance
walk:
  moscow: could
  desc: Walk through nature (with podcast)
  interval: daily
  energize: true
  flow: true
  maslow: safety
pushups:
  interval: daily
  desc: pushups without counting
  moscow: must
  flow: false
  energize: true # physical exercise relaxes the mind
  maslow: safety
  goals:
    - frontlever
hourlypushups:
  moscow: should
  desc: During working hours, 20 pushups per hour
  interval: daily
  energize: true
  flow: false
  maslow: safety
core:
  interval: daily
  desc: 5m plank
  moscow: should
  energize: true
  flow: false
  maslow: safety
  goals:
  - frontlever
run:
  interval: weekly
  moscow: should
  energize: true
  flow: true
  maslow: safety
  goals:
  - marathon
squads:
  interval: daily
  moscow: should
  energize: true
  flow: false
  maslow: safety
  desc: Meditate while wallsquad
handstand:
  moscow: could
  desc: Practice handstand
  interval: daily
  energize: true
  flow: true
  maslow: safety

## Flexibility
stretch:
  interval: daily
  desc: Stretching
  moscow: could
  energize: true
  flow: depends
  maslow: safety
  goals:
  - yogateacher
yoga:
  moscow: could
  energize: true
  flow: true
  interval: daily
  maslow: safety
  goals:
  - yogateacher

## Strength
hourlyexercise:
  moscow: should
  interval: daily
  energize: true
  flow: false
  maslow: safety
  desc: |
    While working from home, we aim to do hourly exercise to build the body.
    We do this with very high weight so we are close to the 1rep max.
    This allows us to do very few reps, resulting in no sweat, but still getting results.
    08:00 one arm pushup L
    09:00 one arm pushup R
    10:00 one arm pullup L
    11:00 one arm pullup R
    12:00 pistol squad L
    13:00 pistol squad R
    14:00 single leg glute bridge L
    15:00 single leg glute bridge R
    16:00 front lever
    17:00 extended plank
    18:00 stretching
# shoulder width stand deadlift for glutes
sprint:
  interval: daily
  moscow: could
  energize: true
  flow: false
  desc: One minute sprint http://youtu.be/SHN-4ve81TY
  maslow: safety
  goals:
  - marathon
wakeupwalk:
  desc: |
    Get natural daylight in your eyes.
    Walk while reconnecting with a friend/neighbor.
    Have calls, send voice messages etc.
  interval: daily
  moscow: should
  energize: true
  flow: true
  maslow: safety



goggins:
  desc: |
    5:30 wakeup
    1.5-2h run
    eat
    45-90min gym
    at night;
    2h stretching/meditation
    spouse
    stationary bike; 3-4days a week
    7-8h sleep

