always_in_car:
  handglovcompartment:
  - EU insurance form (mobielschademelden.nl)
  - EU green card insurance
  - service history
  - asprin
  - chocolate
  - sunscreen
  
  left_door:
  - umbrella
  - bottle water
  - face mask
  
  right_door:
  - bottle water
  - window ice scraper
  
  under_radio:
  - body lotion
  - chewing gum
  
  dashboard:
  - usb charger + cable
  - fog cloth
  
  trunk_hood:
  - tissues/toilet paper
  - start cables
  - emergency triangle
  - first aid kit
  - reflective vest (some countries require you to bring one)
  - spare plastic bag
  - cleaning wipes
  
  trunk:
  - air compressor
  - 2x 1.5L water
  - duct tape
  - multitool with can opener
  - garbage bags
