
type: nestedlist
data:
- $PACKLIST_DIR/sublist/non-physical.yml

- on me:
    hidden-pouch: $PACKLIST_DIR/sublist/hidden-pouch.yml
    backpack (dry-weight 1.2kg):
      laptop compartment:
      - hat
      - to be processed paperwork/notes
      main:
      - intentionally empty for groceries and saving weight
      - spare plastic groceries bag
      - bag of nuts (lunch)
      front (ready for day trip): $PACKLIST_DIR/sublist/day-trip.yml
      sides:
      - carabiners
      - water bottle with clip
      glasses compartment: $PACKLIST_DIR/sublist/clothes/glasses.yml
    jacket / jeans: $PACKLIST_DIR/sublist/motorcycle/jacket.yml

- motorcycle (including 2x 35L givi hard cases):
    clothes of that day: $PACKLIST_DIR/sublist/motorcycle/outfit.yml
    saddle bag (60L baggage roll weekend):
    - spare attachment/lashing strap
    - umbrella
    - instrument (ukulele)
    - second helmet
    - second pair motorcycle (winter) gloves
    - plastic bag:
      - book
      - notebook
    - tissues
    - $PACKLIST_DIR/sublist/miscellaneous.yml
    - plastic bag:
      - dirty laundry
    - $PACKLIST_DIR/sublist/thermo-bag.yml
    - 2x 1.5L water
    - plastic bag:
      - motorcycle cover
    - long steel wire (to lock bag or jacket to motorcycle)
    - $PACKLIST_DIR/sublist/clothes/undies.yml
    handlebar bag with phone case: $PACKLIST_DIR/sublist/motorcycle/front.yml
    L removable case, which I leave on during short stays (35L):
    - plastic bag:
      - winter lining motor gear (held together with kidney belt)
      - motorcycle safety jeans
    - plastic bag:
      - running/walking shoes
    - plastic bag:
      - sandals or flip flops
    - tupperware container: $PACKLIST_DIR/sublist/electronics.yml
    - plastic freezer/seal bag:
      - bluetooth headphones in case
    - $PACKLIST_DIR/sublist/clothes/swim-gear.yml
    R removable case (35L):
    - plastic bag:
      - laptop sleeve:
        - laptop
    - plastic bag: $PACKLIST_DIR/sublist/clothes/clothes.yml
    - $PACKLIST_DIR/sublist/toiletries.yml
    - USB C (work) laptop/phone charger

    tank bag: $PACKLIST_DIR/sublist/motorcycle/tankbag.yml
    under saddle: $PACKLIST_DIR/sublist/motorcycle/under-saddle.yml

- last-minute: $PACKLIST_DIR/sublist/motorcycle/last-minute-moto.yml
